import { TokenType } from "./token.js";

export const KEYWORDS: ReadonlyMap<string, TokenType> = new Map([
  ["int", TokenType.Int],
  ["float", TokenType.Float],
  ["string", TokenType.String],
  ["bool", TokenType.Bool],
  ["void", TokenType.Void],
  ["var", TokenType.Var],
  ["type", TokenType.Type],
  ["struct", TokenType.Struct],
  ["class", TokenType.Class],
  ["interface", TokenType.Interface],
  ["enum", TokenType.Enum],
  ["new", TokenType.New],
  ["this", TokenType.This],
  ["if", TokenType.If],
  ["else", TokenType.Else],
  ["for", TokenType.For],
  ["while", TokenType.While],
  ["return", TokenType.Return],
  ["match", TokenType.Match],
  ["break", TokenType.Break],
  ["continue", TokenType.Continue],
  ["in", TokenType.In],
  ["is", TokenType.Is],
  ["await", TokenType.Await],
  ["try", TokenType.Try],
  ["catch", TokenType.Catch],
  ["Ok", TokenType.Ok],
  ["Err", TokenType.Err],
  ["Result", TokenType.Result],
  ["take", TokenType.Take],
  ["from", TokenType.From],
  ["load", TokenType.Load],
  ["declare", TokenType.Declare],
  ["module", TokenType.Module],
  ["const", TokenType.Const],
  ["true", TokenType.BoolLiteral],
  ["false", TokenType.BoolLiteral],
  ["null", TokenType.NullLiteral],
]);
